### ISSUE TITLE
Mopt fuzzing strategy

### ISSUE THREAD

**Issue by selfbypass** [seemoo-lab/VirtFuzz#3]
Hi, 
Reading the paper, I found that you applied the Mopt fuzzing strategy into VirtFuzz. But I can't find it in codes.
![image](https://github.com/seemoo-lab/VirtFuzz/assets/38554806/16abbb02-a177-4530-95ea-1a75f017dfcb)
I just found these three mutators. So how does VirtFuzz apply it?

**Comment by eknoes** [comment]
Hi!
Indeed you are right. I just searched through the commits of our internal repository, and it seems we have accidentally replaced it with the `StdScheduledMutator` while cleaning up and upgrading some libraries.

See the diff for [fuzz/src/main.rs:743](https://github.com/seemoo-lab/VirtFuzz/blob/main/fuzz/src/main.rs#L743):
```diff
-        let std_mutator = StdMOptMutator::new(
-            &mut state,
-            havoc_mutations(),
-            6,
-            5,
-        )
-        .unwrap();
+        let std_mutator = StdScheduledMutator::new(havoc_mutations());
```

When I have time, I'll add an option to the fuzzer to choose between the different mutators. Thanks for pointing that out!

**Comment by selfbypass** [comment]
> Hi! Indeed you are right. I just searched through the commits of our internal repository, and it seems we have accidentally replaced it with the `StdScheduledMutator` while cleaning up and upgrading some libraries.
> 
> See the diff for [fuzz/src/main.rs:743](https://github.com/seemoo-lab/VirtFuzz/blob/main/fuzz/src/main.rs#L743):
> 
> ```diff
> -        let std_mutator = StdMOptMutator::new(
> -            &mut state,
> -            havoc_mutations(),
> -            6,
> -            5,
> -        )
> -        .unwrap();
> +        let std_mutator = StdScheduledMutator::new(havoc_mutations());
> ```
> 
> When I have time, I'll add an option to the fuzzer to choose between the different mutators. Thanks for pointing that out!

Thanks. It works.
